# Site settings
title: "lucmir"
email: luccmir@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  "Just a documentation of some problems and solution attempts from my daily routine working as a Software Developer."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lucmir.github.io" # the base hostname & protocol for your site
paginate: 20
paginate_path: "/page:num/"

#twitter_username: jekyllrb
github_username:  "lucmir"
linkedin: "https://br.linkedin.com/in/lucas-cunha-a54b896b"

# Build settings
markdown: kramdown

future: false
