# Site settings
title: "lucmir"
email: luccmir@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  "Just a humble Blog to document solutions for my daily problems as a developer."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lucmir.github.io" # the base hostname & protocol for your site
paginate: 20
paginate_path: "/page:num/"

#twitter_username: jekyllrb
github_username:  lucmir

# Build settings
markdown: kramdown

future: false
root: /octo-5
